-- IMPORTANT: Java's LSP (nvim-jdtls) works independently from nvim-lspconfig. NOT INCLUDED HERE.

--  XXX: LANGUAGE REQUIREMENTS:
--
--  XXX: Java: SEE NVIM-JDTLS.LUA IN PLUGINS.
--
-- C++:
-- 1. The 'clangd' LSP via mason.
-- 2. The 'lang.clangd' extra plugin(s) via :LazyExtras
-- 3. The 'Ninja' build tools installed on your system (set as default) and entered into your system environment variables. NOTE: Required for clangd lsp.
-- 4. (optional) The 'codelldb' debug adapter installed via mason. (WE USE THE PATH TO THE CODELLDB.EXE)
--
-- Python:
-- 1. The 'pyright' LSP via mason.
-- 2. The 'lang.python' extra plugin(s) via :LazyExtras
-- 3. (optional) The 'debugpy' debug adapter (python package) installed via mason.
--
-- PowerShell:
-- 1. The 'powershell-editor-services' LSP via mason.
-- 2. (optional) The 'powershell.nvim' plugin for debug support.

-- NOTE: EXAMPLE
-- local lspconfig = require("lspconfig")
-- lspconfig.gopls.setup({
-- settings = {
-- *settings got to do with the golang lsp*
-- }
